baseURL = "https://aamjit.github.io/"
title = "Amarjit Yanglem"
theme = "tinypad"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]

  description = "Does a market decide what you are worth or do you?"
  ctaButton = """<a href="https://www.buymeacoffee.com/amarjit.yanglem"><img src="https://img.buymeacoffee.com/button-api/?text=Buy me a beer&emoji=ðŸº&slug=amarjit.yanglem&button_colour=5F7FFF&font_colour=ffffff&font_family=Cookie&outline_colour=000000&coffee_colour=FFDD00" /></a>"""
  accentColor = "#08F"
  avatarURL = "/images/avatar.webp"
  avatarSize = "size-m"
  AvatarAltText = "avatar"
  ShowBackToTopButton = true # true or false for "back to top" button on posts
  showPostsOnHomePage = "popular"

  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">

    <link rel="icon" type="image/x-icon" href="/images/logo.ico">

    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // â€¢ auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // â€¢ rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """
  socialIcons = [
    {name = "twitter", url = "https://x.com/AamjitY"},
    {name = "linkedin", url = "https://www.linkedin.com/in/amarjit-yanglem/"},
    {name = "stackoverflow", url = "https://stackoverflow.com/users/12891751/aamjit-yanglem"},
    {name = "instagram", url = "https://www.instagram.com/__in_solitude__/"},
    {name = "gmail", url = "mailto:amarjityanglem563@gmail.com"},
    {name = "buymeacoffee", url = "https://buymeacoffee.com/amarjit.yanglem"},
  ]
  metaKeywords = ["blog", "gokarna", "hugo", "portfolio", "amarjit"]

  footer = "Amarjit Yanglem"

[menu]

  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 4

  [[menu.main]]
    name = "Resume"
    pre = "<span data-feather='book'></span>"
    url = "/resume/"
    weight = 4

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 5

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/Aamjit/Aamjit.github.io"
    weight = 6

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
